#### Add e-mail
POST http://localhost:8081/vlaanderen.click/add
Content-Type: application/json

{
  "id": "josé@vermeulen.be"
}

#### Initialize user
POST http://localhost:8081/vlaanderen.click/init
Content-Type: application/json

{
  "id": "SVPkFCUoA8"
}

#### Register
POST http://localhost:8081/vlaanderen.click/register
Content-Type: application/json

{
  "id": "SVPkFCUoA8",
  "voornaam": "Jos",
  "achternaam": "Vermeulen",
  "email": "jos@vermeulen.be",
  "dienst": "Concierges"
}

###
POST http://localhost:8081/vlaanderen.click/stap2
Content-Type: application/json

{
  "id": "SVPkFCUoA8",
  "badgeNummer": "1245678903",
  "telefoonNummer": "00000"
}
